//@version=5
// Author: Akash Sasikumar
// Copyright: 2023.Akash sasikumar
indicator(shorttitle="BB", title="Bollinger Bands", overlay=true, timeframe="", timeframe_gaps=true)

length = input.int(20, title="Length", minval=1)
src = input(close, title="Source")
mult = input.float(2.0, title="StdDev Multiplier", minval=0.001, maxval=50)

basis = ta.sma(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev

offset = input.int(0, "Offset", minval=-500, maxval=500)

basis_plot = plot(basis, "Basis", color=color.orange, offset=offset)
upper_plot = plot(upper, "Upper", color=color.blue, offset=offset)
lower_plot = plot(lower, "Lower", color=color.blue, offset=offset)

fill(upper_plot, lower_plot, color=color.rgb(33, 150, 243, 95), title="Background")

// Highlight overbought/oversold conditions
bgcolor(upper >= high ? color.rgb(255, 169, 82) : na, transp=90)
bgcolor(lower <= low ? color.rgb(97, 76, 175) : na, transp=90)